name = "Dicefire Modpack"
author = "Dicefire Spieletreff Gera e.V."
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a44f2b51e2bf2bfc8e347b73833458b325bfefda22720ffb9f948e2f4df4b38"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
