name = "Dicefire Modpack"
author = "Dicefire Spieletreff Gera e.V."
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b17223b51c2c0f54f2174709a7039247fde1431b7a729b8c4ef38a0a146a2f5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
