name = "Dicefire Modpack"
author = "Dicefire Spieletreff Gera e.V."
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c9d10a644fafeb56a1d847c32bf83a2f91c08905cc1e27591128065fd9675f5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
